### ISSUE TITLE
Table-izing the Armor Page

### ISSUE THREAD

**Issue by Beefnbean** [RoundtableHold/roundtablehold.github.io#125]
Looking to convert the armor lists into tables with columns for: Alterable / Acquisition method
This would be quite the undertaking with 582 pieces so I've broken it down into sub-tasks with 6 sets each. If you have time please take one by converting it into an issue and assigning yourself.

- [ ] 1-6 Traveler's Set (No Helmet) - High Page Set (No Gloves)
- [ ] 7-12 Guardian Set - Blackguard's Iron Mask (Helmet Only)
- [ ] 13-18 Bloodsoaked Set (No Legs) - Raya Lucarian Sorcerer Set
- [ ] 19-24 Lazuli Sorcerer Set - Preceptor's Set
- [ ] 25-30 Mask of Confidence (Helmet Only) - Fia's Set (No Gloves or Legs)
- [ ] 31-36 Deathbed Dress (Chest Only) - Sage Set (No Gloves)
- [ ] 37-42 Greathood (Helmet Only) - Upper-Class Robe (Chest Only)
- [ ] 43-48 Ruler's Set (No Gloves or Legs) - Godskin Apostle Set
- [ ] 49-54 Godskin Noble Set - Imp Heads
- [ ] 55-60 Nox Mirrorhelm (Helmet Only) - Jar (Helmet Only)
- [ ] 61-66 Albinauric Set (No Gloves or Legs) - War Surgeon Set
- [ ] 67-72 Nomadic Merchant's Set (No Gloves) - Godrick Foot Soldier Set
- [ ] 73-78 Raya Lucarian Foot Soldier Set - Highwayman Set
- [ ] 79-84 Vulgar Militia Set - Night Maiden Set
- [ ] 85-90 Champion Set - Raya Lucarian Soldier Set
- [ ] 91-96 Radahn Soldier Set - Kaiden Set
- [ ] 97-102 Land of Reeds Set - Blue Silver Set
- [ ] 103-108 Fire Monk Set - Elden Lord Set
- [ ] 109-114 Knight Set - Cuckoo Knight Set
- [ ] 115-120 Redmane Knight Set - Bloodhound Knight Set
- [ ] 121-126 Cleanrot Set - Blaidd's Set
- [ ] 127-132 Briar Set - Maliketh's Set
- [ ] 133-138 Banished Knight Set - Tree Sentinel Set
- [ ] 139-142 Malformed Dragon Set - General Radahn's Set
- [ ] 143-147 Lionel's Set - Pumpkin Helm (Helmet Only)

**Comment by Beefnbean** [comment]
To make the current headers into tables, the change would look like this:

Current:
```
    title: "Traveler's Set (No Helmet)"
    link: "https://eldenring.wiki.fextralife.com/Traveler's+Set"
    items:
      - ["0", "<a href=\"https://eldenring.wiki.fextralife.com/Traveler's+Clothes\">Traveler's Clothes</a>"]
```

Proposed:
```
    title: "Traveler's Set (No Helmet)"
    link: "https://eldenring.wiki.fextralife.com/Traveler's+Set"
    table: ["Name", "Location", "Notes"]
    items:
      - ["0", "<a href=\"https://eldenring.wiki.fextralife.com/Traveler's+Clothes\">Traveler's Clothes</a>", "Found along with the rest of the set, deep underground in a side room with a large orange flower, adjacent to the Haligtree Roots site of grace.", "Alterable by player"]
```
